### ISSUE TITLE
how to decrypt on Windows + iOS 17.0 ?

### ISSUE THREAD

**Issue by chelaxian** [miticollo/frida-ios-dump#6]
```
(.venv) C:\Users\XXX\iOS\frida\frida-ios-dump>python ./decrypter.py -U -f app.XXX.com
Failed to spawn: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually
```

**Comment by miticollo** [comment]
That message means that on your iDevice frida-server doesn't run. Is your iDevice is jailbreakable?
I didn't test this project on Windows. The main problem could be the permissions of files when Frida transfer it to local. Because permissions between Windows and Unix/maxOS are different.

**Comment by chelaxian** [comment]
> That message means that on your iDevice frida-server doesn't run. Is your iDevice is jailbreakable? I didn't test this project on Windows. The main problem could be the permissions of files when Frida transfer it to local. Because permissions between Windows and Unix/maxOS are different.

A16 with iOS 17.0 with RootHide's BootStrap (no Serotonin). But in-apps tweaks and CLI packages works.
I already installed frida deb from Sileo - re.frida.server 16.1.4 from roothide repo.
if it has no need to be injected in system proccess and so it should work like any other CLI packages.

**Comment by miticollo** [comment]
It cannot work on that environment. Because frida-server is not automatically started. So you must start it manually: open a terminal and type `sudo frida-server`. Even if you do this Frida can't properly inject its agent because that environment is not a full-fledged JB.

**Comment by chelaxian** [comment]
> It cannot work on that environment. Because frida-server is not automatically started. So you must start it manually: open a terminal and type `sudo frida-server`. Even if you do this Frida can't properly inject its agent because that environment is not a full-fledged JB.

i see, thx. so into which proccess Frida Server should inject its agent? what is the name of this proccess? i will wait until something like Serotonine possibly release for iOS 17.0 and try again with manualy injecting Frida to needed system proccess

**Comment by miticollo** [comment]
Well, if you want to use this process means that you want to inject frida agent into the target app (the appt that you want to decrypt).

**Comment by chelaxian** [comment]
> Well, if you want to use this process means that you want to inject frida agent into the target app (the appt that you want to decrypt).

tried this, get:

```
(.venv) L:\iOS\Frida\frida-ios-dump>python ./decrypter.py -U -f app.hiddify.com
Failed to spawn: mach task is gone
```

**Comment by miticollo** [comment]
It corrects. Because you don't have a full-fledged JB. If you want to decrypt an app you can use https://github.com/donato-fiore/TrollDecrypt/releases

**Comment by chelaxian** [comment]
> It corrects. Because you don't have a full-fledged JB. If you want to decrypt an app you can use https://github.com/donato-fiore/TrollDecrypt/releases

ok, sorry. i know that trolldumpers exist, but they don't decrypt plugins and extensions. thought that frida can help

**Comment by miticollo** [comment]
Also this project doesn't decrypt plugins for now. [bagbak](https://github.com/ChiChou/bagbak) does it. Anyway it requires a full-fledged JB.
